name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Rust Codecov
      # You may pin to the exact commit or the version.
      # uses: maboesanman/rust-codecov@59ce25a11e3e218f11e607909cfa7a48f6d926c5
      uses: maboesanman/rust-codecov@v0
          
